name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 734367008253.dkr.ecr.ap-south-1.amazonaws.com

jobs:

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

           # Trivy Filesystem Scan
      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

  build-and-push:

    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Generate Image Tag
      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # Build Docker Images
      - name: Build frontend image
        run: docker build -t $ECR_REGISTRY/url-shortener/frontend:$IMAGE_TAG -f ./frontend/Dockerfile .

      - name: Build link service image
        run: docker build -t $ECR_REGISTRY/url-shortener/link:$IMAGE_TAG -f ./services/link-service/Dockerfile .

      - name: Build redirect service image
        run: docker build -t $ECR_REGISTRY/url-shortener/redirect:$IMAGE_TAG -f ./services/redirect-service/Dockerfile .

      - name: Build stats service image
        run: docker build -t $ECR_REGISTRY/url-shortener/stats:$IMAGE_TAG -f ./services/stats-service/Dockerfile .


      # Trivy Image Scans

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/url-shortener/frontend:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Scan link service image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/url-shortener/link:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Scan redirect service image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/url-shortener/redirect:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Scan stats service image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/url-shortener/stats:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1


      # Push Images to ECR

      - name: Push frontend image
        run: docker push $ECR_REGISTRY/url-shortener/frontend:$IMAGE_TAG

      - name: Push link service image
        run: docker push $ECR_REGISTRY/url-shortener/link:$IMAGE_TAG

      - name: Push redirect service image
        run: docker push $ECR_REGISTRY/url-shortener/redirect:$IMAGE_TAG

      - name: Push stats service image
        run: docker push $ECR_REGISTRY/url-shortener/stats:$IMAGE_TAG


      # Update Kubernetes manifests for ArgoCD

      - name: Update image tag in manifests
        run: |
          sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/api/deployment.yaml
          sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/api/deployment.yaml
          sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/api/deployment.yaml
          sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/api/deployment.yaml


      # Commit updated manifests

      - name: Commit manifest updates
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Update image tag $IMAGE_TAG [skip ci]" || echo "No changes"
          git push
